[versions]
# app version
appVersionName = "1.0"
appVersionCode = "1"
# android platform version
ndkVersion = "26.1.10909125"
targetSdk = "30" # android 11
compileSdk = "34"
minSdk = "24"
agpVersion = "8.6.1"
gradleVersion = "8.7"
kotlin_ver = "1.8.20"
# plugin version
flutterPLuginLoader_ver = "1.0.0"
[libraries]
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agpVersion" }
[plugins]
flutterPluginLoader = { id = "dev.flutter.flutter-plugin-loader", version.ref = "flutterPLuginLoader_ver" }
android-application = { id = "com.android.application", version.ref = "agpVersion" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_ver" }
